FROM mongo:4.4

# Expose MongoDB na portu 30469
EXPOSE 30469

# Spustit MongoDB na vlastním portu a bindnout na všechna rozhraní
# --bind_ip_all zajistí, že Mongo naslouchá i na 0.0.0.0 (důležité při publish portů)
CMD ["mongod", "--port", "30469", "--bind_ip_all"]
